### ISSUE TITLE
Required repo with latest selenide version.

### ISSUE THREAD

**Issue by shailesh7166** [neooleg/selenide-for-c-sharp#3] opened 2017-04-12 09:02 UTC
This is not an issue actually. A humble request rather. :)

The repo is working fine with the selenide 3.0.  Great work.

Can we get the updated repo with latest selenide version?

Or at lest how to do steps to work with latest selenide version with C#.

Thanks!
Shailesh

**Comment by DimaDubyk** [comment] 2017-04-12 11:41
HI,
We can add wiki page later this week (maybe even today). For now you can use our commits to understand how to update selenide sources and also there is a bat file to generate proxies automatically. So you can wait for wiki page or try to make update by yourself. Feel free to make pull requests.

With best regards,
Dima & Oleg

**Comment by shailesh7166** [comment] 2017-04-12 12:06
Hi Dima,

Thanks for the quick response.
I have tried to update it but did not get success. 
My be doing wrong or missing important things.
Unable to load the class files as shown in attachment.
![selenidecerror](https://cloud.githubusercontent.com/assets/27341592/24956510/8e0877c6-1fa5-11e7-9849-f3a8639ac3df.png)

Note: I do not have the latest selenide.proxies.clr.jar file. Where to get it or how to generate it. Would be great help in wiki.
Wiki page sounds great. i will wait for the wiki page.

Thanks in advance! :)

Regards,
Shailesh

**Comment by DimaDubyk** [comment] 2017-04-13 07:32
Hi, Shailesh.
It is not a trivial changes to update selenide version and need further investigation.
Will try to find some time this weekend to investigate. Is it emergent for you?
Regards,
Dima & Oleg

**Comment by shailesh7166** [comment] 2017-04-15 05:23
Hello Dima,

Nope , but I am happy to know that you will going to dig into it.

I will wait for your response and the wiki updates.

Regards,
Shailesh

**Comment by DimaDubyk** [comment] 2017-04-18 06:23
Hi, Shailesh

We spent some time this weekend, but with no luck.
There are several issues that we need to fix in proxygen, so build script works again.
This is about support enums inside interface:
https://github.com/jni4net/jni4net/issues/39
and maybe this to avoid cmd max length restriction
https://github.com/jni4net/jni4net/issues/31
so it will work out of the box without any without extra coding.

We got the error on stage, when we run test project. Root cause is issue that this LogEvent interface contains enum inside and enum code is not generated by proxygen.
https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/logevents/LogEvent.java

What was done: 
We excluded LogEvent.java from artifacts/build.cmd, generated by proxygen and extracted cmd parameters as described in https://github.com/jni4net/jni4net/issues/31, so selenide-4.4.2.proxies.clr.jar file was generated, but we got an error in test project runtime.
'Can't load java class for com.codeborne.selenide.logevents.LogEvent_ from classLoader sun.misc.Launcher$AppClassLoader@c387f44'

So for now issue is not solved.

Also I have started to add steps how to update selenide version:
SO here what we have for now:
1. Update selenide sources with all dependencies to latest versions in .\src\bin folder
Hint: selenide latest version with dependencies can be found here:
https://github.com/codeborne/selenide/blob/master/CHANGELOG
https://mvnrepository.com/artifact/com.codeborne/selenide

2. Update selenide version in build.cmd file
2.1. Optional: Update msbuild version and msbuild path in build.cmd file

3. Run build.cmd from root folder file to generate all proxies.

4. Open generated .\artifacts\proxies\clr\selenide-x.x.x.proxies.clr.csproj
4.1. Include new files, exclude non existing files
4.2. Build .\artifacts\proxies\clr\selenide-x.x.x.proxies.clr.csproj project

5. Update .\artifacts\proxies\clr\selenide-x.x.x.proxies.clr.csproj to .\src\proxies folder

6. Run build.cmd from root folder to compile all the code.

7. Run artifacts\TestSelenideForNet.exe to ensure that selenide works

Useful materials
https://github.com/jni4net/jni4net/wiki/Generating-Proxies

Troubleshooting:
TBA

**Comment by DimaDubyk** [comment] 2017-06-12 19:25
Hi, Shailesh,
I have approved pull request. Please check if issue is fixed for you and I can close this ticket.
Also want to say thanks to Andrey for his contribution.

**Comment by neooleg** [comment] 2017-06-19 08:21
Closing this as fixed, otherwise @shailesh7166 will report and I'll reopen.

**Closed as completed by neooleg** 2017-06-19 08:21 UTC
